import { NextRequest, NextResponse } from "next/server";
import path from "node:path";
import ExcelJS from "exceljs";

export const runtime = "nodejs";
const num = (v: unknown) => Number(v) || 0;
const calc = (p: any) => {
  const cartons = num(p.pcsCtn) > 0 ? Math.ceil(num(p.qty) / num(p.pcsCtn)) : 0;
  const amount = Number((num(p.qty) * num(p.price)).toFixed(2));
  const cbm = Number((num(p.l) * num(p.w) * num(p.h) / 1e6).toFixed(4));
  return { cartons, amount, final: Number((amount - num(p.freeAmount) - num(p.discount)).toFixed(2)), tnw: Number((num(p.nw) * cartons).toFixed(3)), tgw: Number((num(p.gw) * cartons).toFixed(3)), cbm, totalCbm: Number((cbm * cartons).toFixed(4)) };
};

function buildCustomsWorkbook(s:any,totals:any){
  const book=new ExcelJS.Workbook(),ws=book.addWorksheet("报关资料",{pageSetup:{paperSize:9,orientation:"landscape",fitToPage:true,fitToWidth:1,fitToHeight:1,margins:{left:.12,right:.12,top:.2,bottom:.2,header:.05,footer:.05}}});
  ws.views=[{showGridLines:false}];[8,14,26,18,18,18,18,18,15,16].forEach((w,i)=>ws.getColumn(i+1).width=w);
  const border={top:{style:"thin" as const},left:{style:"thin" as const},bottom:{style:"thin" as const},right:{style:"thin" as const}};
  const merge=(range:string,value:any,opts:any={})=>{ws.mergeCells(range);const c=ws.getCell(range.split(":")[0]);c.value=value;c.font={name:"宋体",size:9,...opts.font};c.alignment={vertical:"top",wrapText:true,...opts.alignment};};
  const box=(range:string,value:any,opts:any={})=>{merge(range,value,opts);const [a,b]=range.split(":"),from=ws.getCell(a),to=ws.getCell(b||a);for(let r=Number(from.row);r<=Number(to.row);r++)for(let c=Number(from.col);c<=Number(to.col);c++)ws.getCell(r,c).border=border;};
  for(let r=1;r<=31;r++)ws.getRow(r).height=22;
  ws.getRow(1).height=34;merge("A1:J1","中华人民共和国海关出口货物报关单",{font:{size:15,bold:true},alignment:{horizontal:"center",vertical:"middle"}});
  merge("A2:C2","预录入编号：");merge("D2:G2","海关编号：");merge("H2:J2","页码/页数： 1/1",{alignment:{horizontal:"right"}});
  box("A3:B4",`境内发货人\n${s.seller.cn||s.seller.name||""}`);box("C3:D4",`出境关别\n${s.transport.customsOffice||""}`);box("E3:F4",`出口日期\n${s.basic.shipDate||""}`);box("G3:H4",`申报日期\n${s.basic.invoiceDate||""}`);box("I3:J4",`备案号\n${s.basic.recordNo||""}`);
  box("A5:B6",`境外收货人\n${s.buyer.name||""}`);box("C5:D6",`运输方式\n${s.transport.mode||"海运"}`);box("E5:F6",`运输工具名称及航次号\n${[s.transport.vessel,s.transport.voyage].filter(Boolean).join(" / ")}`);box("G5:H6",`提运单号\n${s.transport.bl||""}`);box("I5:J6",`许可证号\n${s.transport.licenseNo||""}`);
  box("A7:B8",`生产销售单位\n${s.seller.cn||s.seller.name||""}`);box("C7:D8","监管方式\n一般贸易");box("E7:F8","征免性质\n一般征税");box("G7:H8",`合同协议号\n${s.basic.contractNo||s.basic.poNo||""}`);box("I7:J8",`贸易国（地区）\n${s.buyer.country||""}`);
  box("A9:B10",`运抵国（地区）\n${s.buyer.country||""}`);box("C9:D10",`指运港\n${s.transport.discharge||""}`);box("E9:F10",`离境口岸\n${s.transport.loading||""}`);box("G9:H10",`包装种类/件数\n纸箱 / ${totals.cartons}`);box("I9:I10",`毛重\n${totals.gw}`);box("J9:J10",`净重\n${totals.nw}`);
  box("A11:B12",`成交方式\n${String(s.basic.incoterm||"").split(" ")[0]}`);box("C11:D12",`运费\n${s.transport.freight||""}`);box("E11:F12",`保费\n${s.transport.insurance||""}`);box("G11:H12",`杂费\n${s.transport.otherCharges||""}`);box("I11:J12",`境内货源地\n${s.transport.domesticOrigin||"待人工确认"}`);
  box("A13:J14",`随附单证及编号\n发票、装箱单、报关单、报关委托书、进港箱单；发票号：${s.basic.invoiceNo||""}`);
  box("A15:J17",`标记唛码及备注\n${s.products.map((p:any)=>p.mark).filter(Boolean).join(" / ")||"N/M"}`);
  const headRow=18,headers=["项号","商品编号","商品名称及规格型号","数量及单位","单价/总价/币制","原产国（地区）","最终目的国（地区）","境内货源地","征免","备注"];
  headers.forEach((h,i)=>{const c=ws.getCell(headRow,i+1);c.value=h;c.font={name:"宋体",size:9};c.alignment={horizontal:"center",vertical:"middle",wrapText:true};c.border=border});ws.getRow(headRow).height=35;
  const rows=Math.max(1,s.products.length);for(let i=0;i<rows;i++){const p=s.products[i]||{},r=headRow+1+i,c=calc(p),values=[i+1,p.hs||"",`${p.zh||""}\n${p.model||""}\n${p.declaration||""}`,`${p.qty||""} ${p.unit||""}`,`${p.price||""} / ${c.final||""} / ${s.basic.currency||""}`,p.origin||s.basic.origin||"中国",s.buyer.country||"",s.transport.domesticOrigin||"待人工确认","照章征税",p.remark||""];values.forEach((v:any,j:number)=>{const x=ws.getCell(r,j+1);x.value=v;x.border=border;x.font={name:"宋体",size:8};x.alignment={horizontal:j===2?"left":"center",vertical:"middle",wrapText:true}});ws.getRow(r).height=74;}
  const end=headRow+rows;box(`A${end+1}:J${end+2}`,`申报要素及其他说明\n${s.products.map((p:any)=>p.declaration||[p.material&&`材质：${p.material}`,p.usage&&`用途：${p.usage}`].filter(Boolean).join("；")).join("\n")}`);
  box(`A${end+3}:J${end+4}`,"无品牌，出口货物不能确定在最终目的国（地区）享受优惠关税");
  box(`A${end+5}:B${end+7}`,"报关人员\n税之法律责任\n申报单位");box(`C${end+5}:D${end+7}`,"报关人员证号");box(`E${end+5}:F${end+7}`,"电话");box(`G${end+5}:H${end+7}`,"兹申明对以上内容承担如实申报、依法纳税之法律责任\n申报单位（签章）");box(`I${end+5}:J${end+7}`,"海关批注及签章");
  ws.pageSetup.printArea=`A1:J${end+7}`;ws.headerFooter.oddFooter="第 &P 页，共 &N 页";return book;
}

function addStamp(book:ExcelJS.Workbook,ws:ExcelJS.Worksheet,range:{tl:{col:number;row:number};ext:{width:number;height:number}}){const id=book.addImage({filename:path.join(process.cwd(),"public","ac-pkg-stamp.png"),extension:"png"});ws.addImage(id,range);}
const thin={top:{style:"thin" as const},left:{style:"thin" as const},bottom:{style:"thin" as const},right:{style:"thin" as const}};
function styleBox(ws:ExcelJS.Worksheet,fromRow:number,toRow:number,fromCol:number,toCol:number){for(let r=fromRow;r<=toRow;r++)for(let c=fromCol;c<=toCol;c++){const x=ws.getCell(r,c);x.border=thin;x.alignment={vertical:"top",wrapText:true};x.font={name:"Arial",size:9}}}

function buildCertificateWorkbook(s:any){const book=new ExcelJS.Workbook(),ws=book.addWorksheet("Certificate Application",{pageSetup:{paperSize:9,orientation:"portrait",fitToPage:true,fitToWidth:1,fitToHeight:1,margins:{left:.25,right:.25,top:.3,bottom:.3,header:.1,footer:.1}}});ws.views=[{showGridLines:false}];[11,11,11,11,11,11,9,9,9,11].forEach((w,i)=>ws.getColumn(i+1).width=w);for(let r=1;r<=28;r++)ws.getRow(r).height=22;
 ws.mergeCells("A1:E5");ws.getCell("A1").value=`1. Exporter 发货人\n${s.seller.name}\n${s.seller.address}\n${s.seller.phone}  ${s.seller.email}`;ws.mergeCells("F1:J5");ws.getCell("F1").value="Certificate no.:\n\nCERTIFICATE OF ORIGIN\nOF\nTHE PEOPLE'S REPUBLIC OF CHINA";ws.getCell("F1").font={name:"Times New Roman",size:13,bold:true};ws.getCell("F1").alignment={horizontal:"center",vertical:"middle",wrapText:true};
 ws.mergeCells("A6:E10");ws.getCell("A6").value=`2. Consignee 收货人\n${s.consignee.name||s.buyer.name}\n${s.consignee.address||s.buyer.address}\n${s.consignee.country||s.buyer.country}`;ws.mergeCells("F6:J17");ws.getCell("F6").value="5. For certifying authority use only\n签证机构专用";
 ws.mergeCells("A11:E14");ws.getCell("A11").value=`3. Means of transport and route 运输路线\n${s.transport.loading||""}, CHINA → ${s.transport.discharge||""}\n${s.transport.mode||""}`;ws.mergeCells("A15:E17");ws.getCell("A15").value=`4. Country/region of destination 目的地\n${s.buyer.country||""}`;
 const heads=[["A18:B18","6. Marks and number\n唛头"],["C18:E18","7. Number and kind of packages / description of goods\n品名及箱数"],["F18:G18","8. H.S.Code"],["H18:H18","9. Quantity\n数量"],["I18:J18","10. Number and date of invoices\n发票号及日期"]];for(const [rg,text] of heads){ws.mergeCells(rg);ws.getCell(rg.split(":")[0]).value=text}const marks=s.products.map((p:any)=>p.mark).filter(Boolean).join(" / ")||"N/M",desc=s.products.map((p:any)=>`${p.en||p.zh} (${calc(p).cartons} CTNS)`).join("\n"),hs=[...new Set(s.products.map((p:any)=>p.hs).filter(Boolean))].join(" / "),qty=s.products.map((p:any)=>`${p.qty} ${p.unit}`).join("\n");ws.mergeCells("A19:B24");ws.getCell("A19").value=marks;ws.mergeCells("C19:E24");ws.getCell("C19").value=desc;ws.mergeCells("F19:G24");ws.getCell("F19").value=hs;ws.mergeCells("H19:H24");ws.getCell("H19").value=qty;ws.mergeCells("I19:J24");ws.getCell("I19").value=`${s.basic.invoiceNo||""}\n${s.basic.invoiceDate||""}`;ws.mergeCells("A25:E28");ws.getCell("A25").value=`11. Declaration by the exporter\n出口商声明\nPlace: ${s.certificate.place||"Guangzhou"}  Date: ${s.certificate.date||s.basic.invoiceDate||""}`;ws.mergeCells("F25:J28");ws.getCell("F25").value="12. Certification\n签证机构认证区域";styleBox(ws,1,28,1,10);ws.getCell("A1").font={name:"Arial",size:9};ws.getCell("A25").font={name:"Arial",size:9};ws.headerFooter.oddFooter="APPLICATION DATA ONLY / 原产地证申请资料，非正式签发证书    第 &P 页";return book}

function buildBookingWorkbook(s:any,totals:any){const book=new ExcelJS.Workbook(),ws=book.addWorksheet("BOOKING NOTE",{pageSetup:{paperSize:9,orientation:"portrait",fitToPage:true,fitToWidth:1,fitToHeight:1,margins:{left:.2,right:.2,top:.25,bottom:.25,header:.1,footer:.1}}});ws.views=[{showGridLines:false}];for(let i=1;i<=10;i++)ws.getColumn(i).width=11;for(let r=1;r<=30;r++)ws.getRow(r).height=20;ws.mergeCells("A1:E5");ws.getCell("A1").value=`SHIPPER（发货人）\n${s.seller.name}\n${s.seller.cn}\n${s.seller.address}\nEmail: ${s.seller.email}\nTel: ${s.seller.phone}`;ws.mergeCells("F1:J5");ws.getCell("F1").value=`BOOKING NO.（托运单号）\n${s.transport.booking||""}`;ws.mergeCells("A6:E9");ws.getCell("A6").value=`CONSIGNEE（收货人）\n${s.consignee.name||s.buyer.name}\n${s.consignee.address||s.buyer.address}`;ws.mergeCells("F6:J9");ws.getCell("F6").value="BOOKING NOTE";ws.getCell("F6").font={name:"Arial",size:15,bold:true};ws.getCell("F6").alignment={horizontal:"center",vertical:"middle"};ws.mergeCells("A10:E13");ws.getCell("A10").value=`NOTIFY PARTY（通知人）\n${s.notify.name||s.consignee.name||s.buyer.name}\n${s.notify.address||s.consignee.address||s.buyer.address}`;ws.mergeCells("F10:J13");ws.getCell("F10").value=`CY/CY  □    CFS/CFS  □    OTHERS  □\nB/L NO#: ${s.transport.bl||""}\nJOB NO#: ${s.transport.warehouseNo||""}\nContainer: ${s.transport.containerQty||""} × ${s.transport.containerType||""}`;const route=[["A14:C15",`OCEAN VES/VOY#（船名航次）\n${s.transport.vessel||""} ${s.transport.voyage||""}`],["D14:E15",`PORT OF LOADING（装货港）\n${s.transport.loading||""}`],["F14:H15",`PORT OF DISCHARGE（卸货港）\n${s.transport.discharge||""}`],["I14:J15",`PLACE OF DELIVERY（目的港）\n${s.transport.destination||""}`]];for(const [rg,text] of route){ws.mergeCells(rg);ws.getCell(rg.split(":")[0]).value=text}const heads=[["A16:C17","MARKS & NO.\n箱唛标记及号码"],["D16:F17","NUMBER AND KIND OF PACKAGES & DESCRIPTION OF GOODS\n件数及包装种类与货名"],["G16:H17","GROSS WEIGHT (KGS)\n毛重"],["I16:J17","MEASR. (CBM)\n尺码（立方米）"]];for(const [rg,text] of heads){ws.mergeCells(rg);const c=ws.getCell(rg.split(":")[0]);c.value=text;c.font={name:"Arial",size:9,bold:true};c.alignment={horizontal:"center",vertical:"middle",wrapText:true}}ws.mergeCells("A18:C23");ws.getCell("A18").value=s.products.map((p:any)=>p.mark).filter(Boolean).join(" / ")||"N/M";ws.mergeCells("D18:F23");ws.getCell("D18").value=`${totals.cartons} CARTONS\n${s.transport.commodity||s.products.map((p:any)=>p.en).join(", ")}`;ws.mergeCells("G18:H23");ws.getCell("G18").value=`${totals.gw} KGS`;ws.mergeCells("I18:J23");ws.getCell("I18").value=`${totals.cbm} CBM`;ws.mergeCells("A24:F30");ws.getCell("A24").value=`托运条款 / SPECIAL INSTRUCTIONS\n${s.transport.special||""}\nWarehouse: ${s.transport.warehouse||""}\nSI Cutoff: ${s.transport.siCutoff||""}`;ws.mergeCells("G24:J30");ws.getCell("G24").value=`运费支付人：${s.transport.forwarder||""}\n\n托运人：${s.seller.contact||""}\n\nDate: ${s.basic.shipDate||""}`;styleBox(ws,1,30,1,10);return book}

function buildBookingWorkbookV2(s:any,totals:any){
 const book=new ExcelJS.Workbook(),ws=book.addWorksheet("BOOKING NOTE",{pageSetup:{paperSize:9,orientation:"portrait",fitToPage:true,fitToWidth:1,fitToHeight:1,margins:{left:.12,right:.12,top:.15,bottom:.15,header:.05,footer:.05}}});ws.views=[{showGridLines:false}];for(let i=1;i<=10;i++)ws.getColumn(i).width=11;for(let r=1;r<=38;r++)ws.getRow(r).height=19;
 const box=(range:string,value:any,opts:any={})=>{ws.mergeCells(range);const [a,b]=range.split(":"),from=ws.getCell(a),to=ws.getCell(b||a),top=ws.getCell(a);top.value=value;top.font={name:"Arial",size:9,...opts.font};top.alignment={vertical:"top",wrapText:true,...opts.alignment};for(let r=Number(from.row);r<=Number(to.row);r++)for(let c=Number(from.col);c<=Number(to.col);c++)ws.getCell(r,c).border=thin};
 box("A1:E5",`SHIPPER（发货人）\n${s.seller.name||""}\n${s.seller.cn||""}\n${s.seller.address||""}\nEmail: ${s.seller.email||""}\nTel: ${s.seller.phone||""}`);box("F1:J5",`BOOKING NO.（托运单号）\n${s.transport.booking||""}`);
 box("A6:E10",`CONSIGNEE（收货人）\n${s.consignee.name||s.buyer.name||""}\n${s.consignee.contact||s.buyer.contact||""}\n${s.consignee.address||s.buyer.address||""}\n${s.consignee.phone||s.buyer.phone||""}`);box("F6:J10",`BOOKING NOTE\n\nTEL: ${s.transport.forwarderPhone||""}, FAX: ${s.transport.fax||""}, CTC: ${s.transport.forwarderContact||""}`,{font:{size:12,bold:true},alignment:{horizontal:"center",vertical:"middle"}});
 box("A11:E14",`NOTIFY PARTY（通知人）\n${s.notify.name||s.consignee.name||s.buyer.name||""}\n${s.notify.address||s.consignee.address||s.buyer.address||""}`);box("F11:J14",`CY/CY（   ）   CFS/CFS（   ）   OTHERS（   ）\nB/L NO#  ${s.transport.bl||""}          JOB NO#  ${s.transport.warehouseNo||""}\n20′ ___  40′ ___  40′HQ ___  45′ ___  RR（ ）\nCBM ${totals.cbm}   毛重 ${totals.gw} KGS\n装货日期：${s.basic.shipDate||s.transport.etd||""}   提单份数：___正___副\n装货地点：${s.transport.warehouse||""}`);
 box("A15:E18",`FREIGHT & CHARGE：____（ ）PREPAID 预付\n（运费及附加费） HKD ______（ ）COLLECT 到付\n投保金额：________  发票号：${s.basic.invoiceNo||""}\n投保类别：________  付款期限：${s.basic.payment||""}`);box("F15:J18",`SPECIAL REQUIREMENTS / 特别要求\n${s.transport.special||""}`);
 box("A19:C21",`OCEAN VES/VOY#（船名航次）\n${s.transport.vessel||""} ${s.transport.voyage||""}`);box("D19:E21",`PORT OF LOADING（装货港）\n${s.transport.loading||""}`);box("F19:H21",`PORT OF DISCHARGE（卸货港）\n${s.transport.discharge||""}`);box("I19:J21",`PLACE OF DELIVERY（目的港）\n${s.transport.destination||""}`);
 const heads=[["A22:C23","MARKS & NO.\n箱唛标记及号码"],["D22:F23","NUMBER AND KIND OF PACKAGES & DESCRIPTION OF GOODS\n件数及包装种类与货名"],["G22:H23","GROSS WEIGHT (KGS)\n毛重（公斤）"],["I22:J23","MEASR. (CBM)\n尺码（立方数）"]];for(const [rg,text] of heads)box(rg,text,{font:{bold:true},alignment:{horizontal:"center",vertical:"middle"}});
 const rows=Math.max(2,s.products.length),start=24;for(let i=0;i<rows;i++){const p=s.products[i]||{},c=calc(p),r=start+i,blank="\u00A0";box(`A${r}:C${r}`,i===0?(p.mark||"N/M"):(p.mark||blank));box(`D${r}:F${r}`,p.en||p.zh||blank);box(`G${r}:H${r}`,p.en||p.zh?`${c.tgw} KGS`:blank);box(`I${r}:J${r}`,p.en||p.zh?`${c.totalCbm} CBM`:blank);ws.getRow(r).height=30;}
 const end=start+rows-1,terms=`托运条款：\n1. 托运人请按运输惯例及有关责任要求正确填写托运单位；\n2. 因填写错误或资料不全引起的货损、延误由托运人承担；\n3. 运费与附加费按双方协定金额结算；\n4. 托运人应按付款时间结清全部运费；\n5. 货名及重量必须填报清楚并符合运输条款；\n6. 托运人必须由经办人签名并盖公司有效印章。`;
 box(`A${end+1}:F${end+8}`,terms);box(`G${end+1}:J${end+8}`,`运费支付人：${s.transport.forwarder||""}\n\n托运人：${s.seller.contact||""}\n\n日期：${s.basic.shipDate||""}`);ws.pageSetup.printArea=`A1:J${end+8}`;return book;
}

export async function POST(req: NextRequest) {
  try {
    const { shipment: s, type, includeStamp=false } = await req.json();
    if (!s || !type) return NextResponse.json({ error: "Invalid data" }, { status: 400 });
    s.seller=s.seller||{};s.buyer=s.buyer||{};s.consignee=s.consignee||s.buyer;s.notify=s.notify||s.consignee;s.certificate=s.certificate||{};s.basic=s.basic||{};s.transport=s.transport||{};s.products=s.products||[];
    const totals = s.products.reduce((a: any, p: any) => { const c = calc(p); return { qty: a.qty + num(p.qty), cartons: a.cartons + c.cartons, amount: a.amount + c.amount, free: a.free + num(p.freeAmount), final: a.final + c.final, nw: a.nw + c.tnw, gw: a.gw + c.tgw, cbm: a.cbm + c.totalCbm }; }, { qty: 0, cartons: 0, amount: 0, free: 0, final: 0, nw: 0, gw: 0, cbm: 0 });
    const packingProducts=(s.packingProducts?.length?s.packingProducts:s.products),packingTotals=packingProducts.reduce((a:any,p:any)=>{const c=calc(p);return{qty:a.qty+num(p.qty),cartons:a.cartons+c.cartons,nw:a.nw+c.tnw,gw:a.gw+c.tgw,cbm:a.cbm+c.totalCbm}},{qty:0,cartons:0,nw:0,gw:0,cbm:0});
    if(type==="Customs Declaration Data"){
      const customs=buildCustomsWorkbook(s,totals);if(includeStamp)addStamp(customs,customs.getWorksheet("报关资料")!,{tl:{col:7,row:24+s.products.length},ext:{width:220,height:85}});const bytes=await customs.xlsx.writeBuffer();return new NextResponse(Buffer.from(bytes),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":"attachment; filename=ACPKG-Customs-Declaration-Data.xlsx"}});
    }
    if(type==="Certificate of Origin Data"){const cert=buildCertificateWorkbook(s);if(includeStamp)addStamp(cert,cert.getWorksheet("Certificate Application")!,{tl:{col:1,row:25},ext:{width:220,height:80}});const bytes=await cert.xlsx.writeBuffer();return new NextResponse(Buffer.from(bytes),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":"attachment; filename=ACPKG-Certificate-Application-Data.xlsx"}})}
    if(type==="Forwarder Handover Sheet"||type==="Booking Note"){const booking=buildBookingWorkbookV2(s,totals);if(includeStamp)addStamp(booking,booking.getWorksheet("BOOKING NOTE")!,{tl:{col:6,row:30+s.products.length},ext:{width:220,height:80}});const bytes=await booking.xlsx.writeBuffer();return new NextResponse(Buffer.from(bytes),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":"attachment; filename=ACPKG-BOOKING-NOTE.xlsx"}})}
    const book = new ExcelJS.Workbook();
    await book.xlsx.readFile(path.join(process.cwd(), "public", "templates", "clearance-2026-template.xlsx"));
    const keep = type === "Packing List" ? "Packing list" : type === "Sales Contract" ? "Contract" : "Invoice";
    const ws = book.getWorksheet(keep);
    if (!ws) throw new Error("Missing template sheet");
    const set = (address: string, value: string | number | { formula: string; result: number }) => { ws.getCell(address).value = value as never; };
    const buyer = [s.buyer.name, s.buyer.address, [s.buyer.country, s.buyer.contact, s.buyer.email, s.buyer.phone].filter(Boolean).join("\n")].filter(Boolean).join("\n\n");

    if (keep === "Invoice") {
      set("A1", s.seller.name); set("A2", `${s.seller.address}\nPhone: ${s.seller.phone} Email: ${s.seller.email}`); set("A3", "COMMERCIAL INVOICE"); set("B4", buyer); set("G4", `Invoice No: ${s.basic.invoiceNo}\nPayment Terms: ${s.basic.payment}\nDate: ${s.basic.invoiceDate}`); set("A6", s.products.map((p: any) => p.mark).filter(Boolean).join(" / ") || "N/M");
      s.products.slice(0, 3).forEach((p: any, i: number) => { const r = 6 + i, c = calc(p); set(`D${r}`, `${p.en}\n${p.zh}${p.hs?`\nHS code: ${p.hs}`:""}`); set(`E${r}`, p.qty); set(`F${r}`, c.cartons); set(`G${r}`, p.price); set(`H${r}`, { formula: `G${r}*E${r}`, result: c.amount }); });
      set("H9", { formula: "SUM(H6:H8)", result: totals.amount });
      if(type==="Commercial Invoice"){
        const pack=book.getWorksheet("Packing list");if(!pack)throw new Error("Missing packing template");const extra=Math.max(0,packingProducts.length-3);if(extra)pack.insertRows(11,Array.from({length:extra},()=>Array(14).fill(null)),"i");const totalRow=11+extra,pset=(a:string,v:any)=>{pack.getCell(a).value=v};pset("A1",`${s.seller.name}\n${s.seller.address}\nPhone: ${s.seller.phone} Email: ${s.seller.email}`);pset("A2","PACKING LIST");pset("B3",buyer);pset("J3",`Invoice: ${s.basic.invoiceNo}\nDate: ${s.basic.invoiceDate}`);packingProducts.forEach((p:any,i:number)=>{const r=8+i,c=calc(p);[["A",i+1],["B",`${p.en}\n${p.zh}${p.hs?`\nHS code: ${p.hs}`:""}`],["C",p.qty],["D",p.pcsCtn||""],["E",p.l],["F",p.w],["G",p.h],["H",c.cbm],["I",p.nw],["J",p.gw],["K",c.cartons],["L",c.tnw],["M",c.tgw],["N",c.totalCbm]].forEach(([col,v])=>pset(`${col}${r}`,v))});pset(`K${totalRow}`,{formula:`SUM(K8:K${totalRow-1})`,result:packingTotals.cartons});pset(`L${totalRow}`,{formula:`SUM(L8:L${totalRow-1})`,result:packingTotals.nw});pset(`M${totalRow}`,{formula:`SUM(M8:M${totalRow-1})`,result:packingTotals.gw});pset(`N${totalRow}`,{formula:`SUM(N8:N${totalRow-1})`,result:packingTotals.cbm});
      }
    } else if (keep === "Packing list") {
      set("A1", `${s.seller.name}\n${s.seller.address}\nPhone: ${s.seller.phone} Email: ${s.seller.email}`); set("A2", "PACKING LIST"); set("B3", buyer); set("J3", `Invoice: ${s.basic.invoiceNo}\nDate: ${s.basic.invoiceDate}`);
      const extra=Math.max(0,packingProducts.length-3);if(extra)ws.insertRows(11,Array.from({length:extra},()=>Array(14).fill(null)),"i");const totalRow=11+extra;packingProducts.forEach((p: any, i: number) => { const r = 8 + i, c = calc(p); [["A", i + 1], ["B", `${p.en}\n${p.zh}${p.hs?`\nHS code: ${p.hs}`:""}`], ["C", p.qty], ["D", p.pcsCtn||""], ["E", p.l], ["F", p.w], ["G", p.h], ["H", c.cbm], ["I", p.nw], ["J", p.gw], ["K", c.cartons], ["L", c.tnw], ["M", c.tgw], ["N", c.totalCbm]].forEach(([col, value]) => set(`${col}${r}`, value as string | number)); });
      set(`K${totalRow}`, { formula: `SUM(K8:K${totalRow-1})`, result: packingTotals.cartons }); set(`L${totalRow}`, { formula: `SUM(L8:L${totalRow-1})`, result: packingTotals.nw }); set(`M${totalRow}`, { formula: `SUM(M8:M${totalRow-1})`, result: packingTotals.gw }); set(`N${totalRow}`, { formula: `SUM(N8:N${totalRow-1})`, result: packingTotals.cbm });
    } else {
      set("A1", s.seller.name); set("A2", `${s.seller.address}\nPhone: ${s.seller.phone} Email: ${s.seller.email}`); set("E5", s.basic.contractNo || s.basic.piNo); set("E6", s.basic.orderDate);
      s.products.slice(0, 6).forEach((p: any, i: number) => { const r = 9 + i, c = calc(p); set(`A${r}`, `${p.en}\n${p.zh}\n${p.model}`); set(`B${r}`, p.qty); set(`C${r}`, p.unit); set(`D${r}`, p.price); set(`E${r}`, c.final); });
      set("E15", { formula: "SUM(E9:E14)", result: totals.final }); set("A17", `Shipment: ${s.basic.shipDate}`); set("A19", `Port of loading: ${s.transport.loading}`); set("C19", `Port of Destination: ${s.transport.discharge}`); set("A20", s.contract);
    }
    if(type==="Proforma Invoice"){ws.getCell("H3").value="报关资料";ws.getCell("H3").font={name:"宋体",size:10,bold:true,color:{argb:"FFC00000"}}}if(type==="Sales Contract"){ws.getCell("E4").value="报关资料";ws.getCell("E4").font={name:"宋体",size:10,bold:true,color:{argb:"FFC00000"}}}
    const retained=type==="Commercial Invoice"?new Set(["Invoice","Packing list"]):new Set([keep]);for (const sheet of [...book.worksheets]) if (!retained.has(sheet.name)) book.removeWorksheet(sheet.id);if(includeStamp)for(const sheet of book.worksheets)addStamp(book,sheet,{tl:{col:Math.max(4,sheet.columnCount-3),row:Math.max(12,sheet.rowCount)},ext:{width:210,height:78}});
    for(const sheet of book.worksheets){sheet.pageSetup.paperSize=9;sheet.pageSetup.orientation=sheet.name==="Packing list"?"landscape":"portrait";sheet.pageSetup.fitToPage=true;sheet.pageSetup.fitToWidth=1;sheet.pageSetup.fitToHeight=1;sheet.pageSetup.margins={left:.2,right:.2,top:.25,bottom:.25,header:.1,footer:.1};sheet.pageSetup.horizontalCentered=true;sheet.pageSetup.verticalCentered=false;if(sheet.name==="Invoice")sheet.pageSetup.printArea="A1:H9";if(sheet.name==="Packing list")sheet.pageSetup.printArea=`A1:N${Math.max(11,8+packingProducts.length)}`;}
    book.calcProperties.fullCalcOnLoad = true;
    const bytes = await book.xlsx.writeBuffer();
    return new NextResponse(Buffer.from(bytes), { headers: { "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Content-Disposition": `attachment; filename="ACPKG-${keep.replaceAll(" ", "-")}.xlsx"` } });
  } catch (error) {
    console.error("Shipping document export failed", error);
    return NextResponse.json({ error: "Export failed" }, { status: 500 });
  }
}
