import Link from "next/link";
import { CheckCircle2,Database,ExternalLink,ShieldCheck } from "lucide-react";
import { saveSetup } from "./actions";

const field="mt-2 w-full border border-[#ded5c6] rounded-xl px-3 py-3 outline-none focus:ring-2 focus:ring-[#c79f52]/30";
export default async function SetupPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
  const {error,success}=await searchParams;
  return <main className="min-h-screen bg-[#f7f2e8] p-5 lg:p-10"><div className="max-w-3xl mx-auto"><div className="text-[#173b34] font-semibold text-xl">Anne小富婆CRM</div><div className="mt-8 bg-white border border-[#e7dece] rounded-3xl p-6 sm:p-10 shadow-xl shadow-[#173b34]/5">
    {success?<div className="text-center py-8"><CheckCircle2 className="mx-auto text-emerald-600" size={52}/><h1 className="text-3xl font-semibold text-[#173b34] mt-5">配置已安全保存</h1><p className="text-neutral-600 mt-3">请在终端停止并重新运行 <code className="bg-[#f7f2e8] px-2 py-1 rounded">pnpm dev</code>，然后执行 <code className="bg-[#f7f2e8] px-2 py-1 rounded">pnpm db:seed</code> 创建管理员和演示数据。</p><Link href="/login" className="inline-block mt-8 bg-[#173b34] text-white rounded-xl px-6 py-3">返回登录页</Link></div>:<><div className="flex gap-3 items-start"><Database className="text-[#b18436] mt-1"/><div><p className="text-xs tracking-[.2em] text-[#a57d34]">FIRST-TIME SETUP</p><h1 className="text-3xl font-semibold text-[#173b34] mt-2">连接 Supabase 数据库</h1><p className="text-neutral-500 mt-3">参数只会写入本机已被 Git 忽略的 <code>.env.local</code>，不会进入代码仓库。</p></div></div>
    <div className="mt-7 bg-[#f9f5ea] rounded-2xl p-5 text-sm text-neutral-700"><b>还没有 Supabase 项目？</b> 先免费创建项目，然后在 Project Settings → API Keys 复制 Project URL、Publishable/Anon Key 和 Secret/Service Role Key。<a className="ml-2 text-[#8c6726] underline" href="https://supabase.com/dashboard" target="_blank" rel="noreferrer">打开 Supabase <ExternalLink className="inline" size={13}/></a></div>
    {error&&<div className="mt-5 rounded-xl bg-red-50 text-red-700 p-3 text-sm">{error}</div>}
    <form action={saveSetup} className="mt-7 grid gap-5"><label className="text-sm font-medium">Project URL<input className={field} name="url" type="url" required placeholder="https://你的项目编号.supabase.co"/><span className="block text-xs text-neutral-400 mt-1">必须复制完整地址，不要填写“项目 URL”。</span></label><label className="text-sm font-medium">Publishable / Anon Key<textarea className={field} name="anonKey" required rows={3} placeholder="sb_publishable_... 或 eyJ..."/><span className="block text-xs text-neutral-400 mt-1">复制 API Keys 页面中绿色/公开的完整密钥。</span></label><label className="text-sm font-medium">Secret / Service Role Key<textarea className={field} name="serviceKey" required rows={3} placeholder="sb_secret_... 或 eyJ..."/><span className="block text-xs text-neutral-400 mt-1">复制 Secret key 或旧版 service_role key；不要把密钥发送给他人。</span></label><div className="grid sm:grid-cols-2 gap-5"><label className="text-sm font-medium">管理员邮箱<input className={field} name="email" type="email" required defaultValue="anne@example.com"/></label><label className="text-sm font-medium">管理员演示密码<input className={field} name="password" type="password" required minLength={10}/></label></div><div className="flex gap-2 text-xs text-neutral-500"><ShieldCheck size={15}/>Service Role Key 仅用于迁移和创建管理员，绝不会发送到浏览器端。</div><button className="rounded-xl bg-[#173b34] text-white py-3.5 font-medium">验证格式并保存配置</button></form></>}
  </div></div></main>;
}
