import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { ImapFlow } from "imapflow";
import { simpleParser } from "mailparser";

const root = process.cwd();
const configPath = process.env.COMMUNICATION_BRIDGE_CONFIG || path.join(root, "data", "communication-bridge.json");
const statePath = path.join(root, "data", "communication-bridge-state.json");
const maxBody = 90_000;

async function jsonFile(file, fallback) {
  try { return JSON.parse(await fs.readFile(file, "utf8")); } catch { return fallback; }
}

async function saveState(state) {
  await fs.mkdir(path.dirname(statePath), { recursive: true });
  const temporary = `${statePath}.tmp`;
  await fs.writeFile(temporary, JSON.stringify(state, null, 2), "utf8");
  await fs.rename(temporary, statePath);
}

function env(name) {
  const value = process.env[name];
  if (!value) throw new Error(`缺少环境变量 ${name}`);
  return value;
}

function address(list = []) {
  return list[0] || {};
}

function autoGenerated(headers, subject = "") {
  const precedence = String(headers?.get?.("precedence") || "").toLowerCase();
  const autoSubmitted = String(headers?.get?.("auto-submitted") || "").toLowerCase();
  return /bulk|list|junk/.test(precedence) || (autoSubmitted && autoSubmitted !== "no") || /自动回复|auto.?reply|out of office|delivery status|undeliverable/i.test(subject);
}

async function postEvent(config, event) {
  const response = await fetch(`${config.crmUrl.replace(/\/$/, "")}/api/communications/ingest`, {
    method: "POST",
    headers: { authorization: `Bearer ${env(config.secretEnv)}`, "content-type": "application/json" },
    body: JSON.stringify(event),
  });
  if (!response.ok) throw new Error(`CRM ${response.status}: ${(await response.text()).slice(0, 300)}`);
  return response.json();
}

async function syncFolder(config, account, folder, state) {
  const client = new ImapFlow({
    host: account.host,
    port: account.port || 993,
    secure: true,
    auth: { user: account.email, pass: env(account.passwordEnv) },
    logger: false,
  });
  const stateKey = `${account.source}|${folder.name}`;
  let processed = 0;
  try {
    await client.connect();
    const lock = await client.getMailboxLock(folder.name);
    try {
      let startUid = Number(state[stateKey] || 0) + 1;
      if (!state[stateKey]) {
        const since = new Date(Date.now() - (config.initialLookbackHours || 24) * 3_600_000);
        const recent = await client.search({ since }, { uid: true });
        if (!recent.length) {
          state[stateKey] = Number(client.mailbox?.uidNext || 1) - 1;
          return 0;
        }
        startUid = Math.min(...recent);
      }
      for await (const message of client.fetch(`${startUid}:*`, { uid: true, envelope: true, internalDate: true, source: true }, { uid: true })) {
        if (!message.source) continue;
        const parsed = await simpleParser(message.source);
        const own = account.email.toLowerCase();
        const from = address(parsed.from?.value);
        const recipients = [...(parsed.to?.value || []), ...(parsed.cc?.value || [])];
        const outbound = String(from.address || "").toLowerCase() === own || folder.direction === "outbound";
        const counterpart = outbound ? recipients.find((item) => String(item.address || "").toLowerCase() !== own) || recipients[0] || {} : from;
        const subject = parsed.subject || message.envelope?.subject || "";
        const body = String(parsed.text || "").trim().slice(0, maxBody);
        const event = {
          source: account.source,
          externalId: `imap:${folder.name}:${message.uid}:${parsed.messageId || "no-message-id"}`,
          occurredAt: (parsed.date || message.internalDate || new Date()).toISOString(),
          direction: outbound ? "outbound" : "inbound",
          senderName: String(counterpart.name || "").slice(0, 500) || undefined,
          senderEmail: String(counterpart.address || "").toLowerCase() || undefined,
          subject: subject.slice(0, 1000),
          body,
          isRealCustomer: !autoGenerated(parsed.headers, subject),
          needsReply: false,
        };
        await postEvent(config, event);
        state[stateKey] = message.uid;
        await saveState(state);
        processed++;
      }
    } finally { lock.release(); }
  } finally { await client.logout().catch(() => undefined); }
  return processed;
}

async function run() {
  const config = await jsonFile(configPath, null);
  if (!config) throw new Error(`缺少配置文件：${configPath}`);
  const state = await jsonFile(statePath, {});
  let total = 0;
  for (const account of config.emailAccounts || []) {
    for (const folder of account.folders || [{ name: "INBOX", direction: "inbound" }]) {
      try {
        const count = await syncFolder(config, account, folder, state);
        total += count;
        console.log(`[${new Date().toISOString()}] ${account.email} / ${folder.name}: ${count} 封`);
      } catch (error) {
        console.error(`[${new Date().toISOString()}] ${account.email} / ${folder.name}:`, error instanceof Error ? error.message : error);
      }
    }
  }
  console.log(`[${new Date().toISOString()}] 本轮完成，共写入 ${total} 封`);
}

const intervalMinutes = Number(process.env.COMMUNICATION_BRIDGE_INTERVAL_MINUTES || 5);
await run();
if (process.argv.includes("--watch")) setInterval(() => run().catch(console.error), intervalMinutes * 60_000);
