import { createClient } from "@supabase/supabase-js";

const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY,email=process.env.SEED_ADMIN_EMAIL,password=process.env.SEED_ADMIN_PASSWORD;
if(!url||!key||!email||!password) throw new Error("缺少 Supabase 或管理员种子环境变量，请参考 .env.example");
const db=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});
const {data:userData,error:userError}=await db.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:"管理员 Anne",role:"admin"}});
if(userError&&!userError.message.includes("already")) throw userError;
let admin=userData?.user?.id;if(!admin){const {data}=await db.auth.admin.listUsers();admin=data.users.find(u=>u.email===email)?.id}if(!admin)throw new Error("无法定位管理员账号");
await db.from("profiles").update({full_name:"管理员 Anne",role:"admin"}).eq("id",admin);

const cats=["PET瓶","PE瓶","HDPE瓶","PP瓶","PETG瓶","PCR瓶","真空瓶","膏霜罐","化妆品软管","乳液泵","喷雾泵","泡沫泵","香水喷头","瓶盖","唇膏管","香水瓶","滴管瓶","粉底液瓶","纸盒","礼品盒","美妆工具","酒店洗护包装","其他"];
await db.from("product_categories").upsert(cats.map((x,i)=>({category_code:`CAT-${String(i+1).padStart(3,"0")}`,category_name:x,sort_order:i+1})),{onConflict:"category_code"});
const countries=["美国","英国","法国","德国","澳大利亚","加拿大","阿联酋","新加坡"],stages=["有明确询盘","已报价","样品已寄","价格谈判","等待订单","已成交"];
const customers=Array.from({length:20},(_,i)=>({customer_code:`DEMO-CUS-${String(i+1).padStart(3,"0")}`,company_name:`Demo Beauty ${String.fromCharCode(65+i)} Ltd.`,country:countries[i%countries.length],stage:stages[i%stages.length],grade:["A","B","C"][i%3],source:["Google","展会","LinkedIn","转介绍"][i%4],owner_id:admin,next_follow_up_at:i<5?new Date(Date.now()+(i-2)*86400000).toISOString():null,notes:"虚构演示客户"}));
await db.from("customers").upsert(customers,{onConflict:"customer_code"});const {data:cs}=await db.from("customers").select("id,customer_code").like("customer_code","DEMO-%");
const contacts=Array.from({length:30},(_,i)=>({customer_id:cs[i%cs.length].id,full_name:`Demo Contact ${i+1}`,position:["Buyer","Founder","Product Manager"][i%3],email:`contact${i+1}@example.invalid`,whatsapp:`+000000${i+1}`,is_primary:i<20,notes:"虚构联系人"}));await db.from("contacts").insert(contacts);
const opps=Array.from({length:15},(_,i)=>({opportunity_code:`DEMO-OPP-${String(i+1).padStart(3,"0")}`,customer_id:cs[i%cs.length].id,title:`2026 ${["护肤瓶器","酒店洗护","香水包装","礼盒"][i%4]}项目`,status:stages[i%stages.length],estimated_amount:5000+i*1250,currency:"USD",owner_id:admin,expected_close_date:new Date(Date.now()+(i+10)*86400000).toISOString().slice(0,10)}));await db.from("opportunities").upsert(opps,{onConflict:"opportunity_code"});const {data:os}=await db.from("opportunities").select("id,customer_id,title").like("opportunity_code","DEMO-%");
await db.from("follow_ups").insert(Array.from({length:30},(_,i)=>({customer_id:cs[i%cs.length].id,opportunity_id:os[i%os.length].id,channel:["Email","WhatsApp","LinkedIn"][i%3],content:`第 ${i+1} 条演示跟进：确认包装规格与采购计划。`,result:["已回复","待回复","需要报价"][i%3],created_by:admin,followed_at:new Date(Date.now()-i*86400000).toISOString()})));
await db.from("tasks").insert(Array.from({length:20},(_,i)=>({title:`跟进 ${cs[i%cs.length].customer_code}`,task_type:i%3===0?"报价跟进":"客户跟进",customer_id:cs[i%cs.length].id,opportunity_id:os[i%os.length].id,assigned_to:admin,due_at:new Date(Date.now()+(i-6)*86400000).toISOString(),priority:i<8?"高":"中",status:"待处理",auto_rule:i%3===0?"OPPORTUNITY_QUOTED":null})));
const suppliers=Array.from({length:10},(_,i)=>({supplier_code:`DEMO-SUP-${String(i+1).padStart(3,"0")}`,company_name:`优选包装供应商 ${i+1} 号`,supplier_type:i<4?"核心供应商":"常规供应商",main_products:[cats[i],cats[(i+6)%cats.length]],main_materials:[["PET","PP","PCR"][i%3]],standard_moq:10000,lead_time_days:20+i,quality_score:22+i%8,price_score:14+i%6,delivery_score:14+i%6,communication_score:10+i%5,customization_score:7+i%3,after_sales_score:3+i%2,status:"可合作",notes:"虚构演示供应商"})).map(s=>({...s,main_materials:[s.main_materials[0]]}));await db.from("suppliers").upsert(suppliers,{onConflict:"supplier_code"});const [{data:ss},{data:catRows}]=await Promise.all([db.from("suppliers").select("id,supplier_code").like("supplier_code","DEMO-%"),db.from("product_categories").select("id,category_name")]);
const products=Array.from({length:50},(_,i)=>({product_code:`PRD-2026-${String(i+1).padStart(4,"0")}`,product_name:`${cats[i%cats.length]} ${30+(i%10)*20}ml`,product_name_en:`Demo ${cats[i%cats.length]} ${i+1}`,category_id:catRows.find(c=>c.category_name===cats[i%cats.length]).id,material:["PET","PP","HDPE","PETG","PCR"][i%5],capacity_value:30+(i%10)*20,capacity_unit:"ml",neck_size:["18/410","20/410","24/410"][i%3],product_status:i%5===0?"已验证":"可推荐",existing_mold:true,recyclable:i%2===0,search_keywords:`包装 瓶器 ${cats[i%cats.length]}`,tags:["演示",i%2?"护肤":"酒店"],owner_id:admin}));await db.from("products").upsert(products,{onConflict:"product_code"});const {data:ps}=await db.from("products").select("id,product_code").like("product_code","PRD-2026-%");
const sp=[];for(let i=0;i<ps.length;i++)for(let j=0;j<1+(i%3);j++)sp.push({product_id:ps[i].id,supplier_id:ss[(i+j)%ss.length].id,supplier_product_code:`${ss[(i+j)%ss.length].supplier_code}-P${i+1}`,supplier_model:`M-${i+1}-${j+1}`,supplier_product_name:`供应商款 ${i+1}`,material:["PET","PP","HDPE"][i%3],capacity_value:30+(i%10)*20,capacity_unit:"ml",standard_moq:10000,production_lead_time_days:20+j*5,sample_available:true,sample_fee:100,existing_mold:true,mold_ownership:"供应商公模",verification_status:j===0?"已确认报价":"已收到资料",last_verified_at:new Date().toISOString(),preferred_supplier:j===0,status:"可采购"});await db.from("supplier_products").insert(sp);const {data:sps}=await db.from("supplier_products").select("id").like("supplier_product_code","DEMO-%");
for(let i=0;i<sps.length;i++){const {data:q}=await db.from("supplier_quotations").insert({supplier_product_id:sps[i].id,quotation_number:`DEMO-Q-${String(i+1).padStart(4,"0")}`,quotation_version:1,quotation_date:new Date().toISOString().slice(0,10),valid_until:new Date(Date.now()+(i%12)*86400000).toISOString().slice(0,10),currency:i%3===0?"USD":"CNY",exchange_rate:i%3===0?7.2:1,trade_term:i%2?"EXW":"FOB",lead_time_days:25,status:"有效"}).select("id").single();if(q)await db.from("supplier_price_tiers").insert([[10000,29999,.85],[30000,49999,.78],[50000,99999,.72],[100000,null,.65]].map(([min,max,price],n)=>({quotation_id:q.id,minimum_quantity:min,maximum_quantity:max,unit_price:Number(price)+(i%5)*.01,sort_order:n+1})));}
console.log(`演示数据完成：admin=${email}，客户20、联系人30、项目15、产品50、供应商10。`);
