create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create type public.app_role as enum ('admin','sales','purchasing','finance');
create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text not null, role app_role not null default 'sales', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table public.customers (
 id uuid primary key default gen_random_uuid(), customer_code text unique, company_name text not null, website text, customer_role text, main_products text[], business_lines text[], stage text not null default '待开发', grade text default 'C', country text, company_size text, employee_count int,
 source text, latest_result text, next_action text, next_follow_up_at timestamptz, last_follow_up_at timestamptz, owner_id uuid references public.profiles, background_status text, background_summary text, financial_status text, risk_level text default '低', accepts_moq_10000 boolean, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table public.contacts (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers, full_name text not null, position text, email text, phone text, whatsapp text, linkedin text, is_primary boolean default false, notes text, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table public.opportunities (id uuid primary key default gen_random_uuid(), opportunity_code text unique, customer_id uuid not null references public.customers, title text not null, status text not null default '需求确认中', estimated_amount numeric(18,4) default 0, currency char(3) default 'USD', expected_close_date date, owner_id uuid references public.profiles, quoted_at timestamptz, notes text, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table public.follow_ups (id uuid primary key default gen_random_uuid(), customer_id uuid references public.customers, opportunity_id uuid references public.opportunities, contact_id uuid references public.contacts, channel text, content text not null, result text, next_action text, followed_at timestamptz not null default now(), created_by uuid references public.profiles, created_at timestamptz default now(), deleted_at timestamptz);
create table public.tasks (id uuid primary key default gen_random_uuid(), title text not null, task_type text not null default '普通跟进', customer_id uuid references public.customers, opportunity_id uuid references public.opportunities, assigned_to uuid references public.profiles, due_at timestamptz not null, priority text not null default '中', status text not null default '待处理', auto_rule text, completed_at timestamptz, notes text, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles, title text not null, body text, severity text default 'info', entity_type text, entity_id uuid, read_at timestamptz, created_at timestamptz default now());

create table public.suppliers (id uuid primary key default gen_random_uuid(), supplier_code text unique, company_name text not null, supplier_type text, contact_name text, phone text, wechat text, email text, address text, website text, main_products text[], main_materials text[], existing_molds text, standard_moq int, sample_fee numeric(18,4), mold_fee numeric(18,4), payment_terms text, lead_time_days int, can_invoice boolean, supports_export boolean, quality_issue_history text, last_cooperation_date date, quality_score numeric(5,2) default 0, price_score numeric(5,2) default 0, delivery_score numeric(5,2) default 0, communication_score numeric(5,2) default 0, customization_score numeric(5,2) default 0, after_sales_score numeric(5,2) default 0, total_score numeric(5,2) generated always as (quality_score+price_score+delivery_score+communication_score+customization_score+after_sales_score) stored, grade text generated always as (case when quality_score+price_score+delivery_score+communication_score+customization_score+after_sales_score>=85 then 'A' when quality_score+price_score+delivery_score+communication_score+customization_score+after_sales_score>=70 then 'B' when quality_score+price_score+delivery_score+communication_score+customization_score+after_sales_score>=60 then 'C' else 'D' end) stored, status text default '可合作', notes text, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);

create table public.product_categories (id uuid primary key default gen_random_uuid(), parent_id uuid references public.product_categories, category_code text unique not null, category_name text not null, category_name_en text, description text, sort_order int default 0, status text default '启用', created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table public.product_families (id uuid primary key default gen_random_uuid(), family_code text unique not null, family_name text not null, description text, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table public.products (id uuid primary key default gen_random_uuid(), product_code text unique not null, product_name text not null, product_name_en text, product_family_id uuid references public.product_families, category_id uuid references public.product_categories, internal_model text, product_status text default '待整理', business_line text, product_usage text[], material text, capacity_value numeric(12,3), capacity_unit text, neck_size text, shape text, color text, surface_finish text, closure_type text, pump_type text, dosage numeric(12,3), dimensions text, weight_grams numeric(12,3), overflow_capacity numeric(12,3), available_decorations text[], eco_material_options text[], replaceable_inner_container boolean default false, refillable boolean default false, recyclable boolean default false, food_grade boolean default false, existing_mold boolean default false, custom_mold_supported boolean default false, custom_mold_notes text, product_description text, search_keywords text, tags text[], main_image text, specification_data jsonb default '{}', owner_id uuid references public.profiles, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table public.supplier_products (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products, supplier_id uuid not null references public.suppliers, supplier_product_code text, supplier_model text, supplier_product_name text, supplier_product_url text, supplier_category text, material text, capacity_value numeric(12,3), capacity_unit text, neck_size text, available_colors text[], available_accessories text[], existing_mold boolean default false, mold_ownership text, custom_mold_supported boolean default false, mold_fee numeric(18,4), mold_lead_time_days int, sample_available boolean default false, sample_fee numeric(18,4), sample_lead_time_days int, standard_moq int, production_lead_time_days int, monthly_capacity int, packaging_method text, carton_quantity int, carton_dimensions text, gross_weight numeric(12,3), net_weight numeric(12,3), quality_notes text, supplier_contact_id uuid, preferred_supplier boolean default false, verification_status text default '未核实', last_verified_at timestamptz, status text default '可采购', notes text, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create unique index supplier_product_code_active on public.supplier_products(supplier_id,supplier_product_code) where deleted_at is null and supplier_product_code is not null;
create unique index one_preferred_supplier on public.supplier_products(product_id) where preferred_supplier and deleted_at is null;
create table public.supplier_quotations (id uuid primary key default gen_random_uuid(), supplier_product_id uuid not null references public.supplier_products, quotation_number text not null, quotation_version int not null default 1, quotation_date date not null, valid_until date, currency char(3) not null, exchange_rate numeric(18,8), trade_term text not null, tax_included boolean default false, unit text default '个', setup_fee numeric(18,4) default 0, mold_fee numeric(18,4) default 0, printing_plate_fee numeric(18,4) default 0, decoration_fee numeric(18,4) default 0, packaging_fee numeric(18,4) default 0, sample_fee numeric(18,4) default 0, other_fee numeric(18,4) default 0, price_notes text, payment_terms text, lead_time_days int, quotation_file text, quoted_by uuid references public.profiles, is_current boolean default true, status text default '有效', created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz, unique(supplier_product_id,quotation_number,quotation_version));
create table public.supplier_price_tiers (id uuid primary key default gen_random_uuid(), quotation_id uuid not null references public.supplier_quotations, minimum_quantity int not null check(minimum_quantity>0), maximum_quantity int, unit_price numeric(18,6) not null check(unit_price>=0), tier_notes text, sort_order int default 0, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz, check(maximum_quantity is null or maximum_quantity>=minimum_quantity));
create table public.product_files (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products, supplier_product_id uuid references public.supplier_products, file_type text not null, file_name text not null, file_url text not null, file_size bigint, mime_type text, storage_key text, checksum_sha256 text, image_phash text, sort_order int default 0, is_primary boolean default false, uploaded_by uuid references public.profiles, notes text, created_at timestamptz default now(), deleted_at timestamptz);
create table public.product_favorites (user_id uuid references public.profiles, product_id uuid references public.products, created_at timestamptz default now(), primary key(user_id,product_id));
create table public.product_recent_views (user_id uuid references public.profiles, product_id uuid references public.products, viewed_at timestamptz default now(), primary key(user_id,product_id));
create table public.sample_records (id uuid primary key default gen_random_uuid(), product_id uuid references public.products, supplier_product_id uuid references public.supplier_products, opportunity_id uuid references public.opportunities, status text default '申请', requested_at timestamptz, received_at timestamptz, evaluated_at timestamptz, sample_fee numeric(18,4), currency char(3), quality_score numeric(5,2), evaluation_notes text, owner_id uuid references public.profiles, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table public.opportunity_products (id uuid primary key default gen_random_uuid(), opportunity_id uuid not null references public.opportunities, product_id uuid not null references public.products, supplier_product_id uuid references public.supplier_products, selected_price_id uuid references public.supplier_price_tiers, recommendation_status text default '待筛选', recommended_quantity int, customer_target_price numeric(18,6), internal_cost numeric(18,6), customer_quoted_price numeric(18,6), currency char(3), estimated_profit numeric(18,6), estimated_margin numeric(9,4), recommended_at timestamptz, customer_feedback text, selected_for_sample boolean default false, selected_for_order boolean default false, price_snapshot jsonb, notes text, created_by uuid references public.profiles, created_at timestamptz default now(), updated_at timestamptz default now());

create table public.orders (id uuid primary key default gen_random_uuid(), order_number text unique not null, opportunity_id uuid references public.opportunities, customer_id uuid not null references public.customers, status text default '草稿', order_date date default current_date, sales_amount numeric(18,4) default 0, sales_currency char(3) default 'USD', sales_exchange_rate numeric(18,8) default 1, revenue_cny numeric(18,4) generated always as (sales_amount*sales_exchange_rate) stored, total_cost_cny numeric(18,4) default 0, net_profit_cny numeric(18,4) generated always as ((sales_amount*sales_exchange_rate)-total_cost_cny) stored, profit_margin numeric(9,4) generated always as (case when sales_amount*sales_exchange_rate=0 then 0 else (((sales_amount*sales_exchange_rate)-total_cost_cny)/(sales_amount*sales_exchange_rate))*100 end) stored, expected_payment_date date, notes text, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders, source_opportunity_product_id uuid references public.opportunity_products, product_id uuid references public.products, supplier_product_id uuid references public.supplier_products, supplier_id uuid references public.suppliers, product_name_snapshot text not null, specification_snapshot jsonb not null, supplier_name_snapshot text, supplier_model_snapshot text, quantity int not null, sales_unit_price numeric(18,6), sales_currency char(3), sales_amount numeric(18,4), purchase_unit_price numeric(18,6), purchase_currency char(3), purchase_amount numeric(18,4), exchange_rate_snapshot numeric(18,8), decoration_cost numeric(18,4) default 0, mold_cost numeric(18,4) default 0, packaging_cost numeric(18,4) default 0, other_cost numeric(18,4) default 0, total_cost numeric(18,4), gross_profit numeric(18,4), gross_margin numeric(9,4), delivery_status text, notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.receivables (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders, type text, amount numeric(18,4) not null, currency char(3) not null, exchange_rate numeric(18,8) not null, due_date date, received_amount numeric(18,4) default 0, outstanding_amount numeric(18,4) generated always as (amount-received_amount) stored, status text default '待收款', created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table public.payables (id uuid primary key default gen_random_uuid(), order_id uuid references public.orders, supplier_id uuid references public.suppliers, amount numeric(18,4) not null, currency char(3) not null, exchange_rate numeric(18,8) not null, due_date date, paid_amount numeric(18,4) default 0, outstanding_amount numeric(18,4) generated always as (amount-paid_amount) stored, status text default '待付款', created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table public.cost_entries (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders, cost_type text not null, amount numeric(18,4) not null, currency char(3) not null, exchange_rate numeric(18,8) not null, amount_cny numeric(18,4) generated always as (amount*exchange_rate) stored, notes text, created_at timestamptz default now(), deleted_at timestamptz);
create table public.import_batches (id uuid primary key default gen_random_uuid(), file_name text not null, source_type text not null, entity_type text not null, mapping jsonb, total_rows int default 0, success_rows int default 0, failed_rows int default 0, status text default '待处理', error_report jsonb, created_by uuid references public.profiles, created_at timestamptz default now(), completed_at timestamptz);
create table public.audit_logs (id bigint generated always as identity primary key, user_id uuid references public.profiles, entity_type text not null, entity_id text, action text not null, before_data jsonb, after_data jsonb, created_at timestamptz default now());

create index customer_search on public.customers using gin (company_name gin_trgm_ops);
create index product_search on public.products using gin (product_name gin_trgm_ops);
create index product_filters on public.products(category_id,material,capacity_value,neck_size,product_status) where deleted_at is null;
create index task_due on public.tasks(due_at,status) where deleted_at is null;
create index quote_expiry on public.supplier_quotations(valid_until,status,is_current) where deleted_at is null;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),coalesce((new.raw_user_meta_data->>'role')::app_role,'sales')); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.on_opportunity_quoted() returns trigger language plpgsql security definer set search_path=public as $$ begin if new.status='已报价' and old.status is distinct from new.status then insert into tasks(title,task_type,customer_id,opportunity_id,assigned_to,due_at,priority,auto_rule) values('跟进报价：'||new.title,'报价跟进',new.customer_id,new.id,new.owner_id,now()+interval '3 days','高','OPPORTUNITY_QUOTED'); new.quoted_at=now(); end if; return new; end $$;
create trigger opportunity_quoted before update on public.opportunities for each row execute procedure public.on_opportunity_quoted();

alter table public.profiles enable row level security;
do $$ declare t text; begin foreach t in array array['customers','contacts','opportunities','follow_ups','tasks','notifications','suppliers','product_categories','product_families','products','supplier_products','supplier_quotations','supplier_price_tiers','product_files','product_favorites','product_recent_views','sample_records','opportunity_products','orders','order_items','receivables','payables','cost_entries','import_batches','audit_logs'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy authenticated_access on public.%I for all to authenticated using (true) with check (true)',t); end loop; end $$;
create policy own_profile on public.profiles for select to authenticated using(id=auth.uid() or exists(select 1 from profiles p where p.id=auth.uid() and p.role='admin'));

insert into storage.buckets(id,name,public) values('product-files','product-files',false) on conflict do nothing;
create policy product_files_read on storage.objects for select to authenticated using(bucket_id='product-files');
create policy product_files_write on storage.objects for insert to authenticated with check(bucket_id='product-files');
