import { AlertTriangle, ArrowRight, CheckCircle2 } from "lucide-react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { StatCard } from "@/components/stat-card";
import { money, shanghaiDateKey, shortDate } from "@/lib/utils";
import { isLocalMode,localRows } from "@/lib/local-db";

export default async function Dashboard() {
  if(isLocalMode())return <LocalDashboard/>;
  const supabase=await createClient();
  const currentDate=new Date(), today=shanghaiDateKey(currentDate), month=today.slice(0,7);
  const expiryLimit=new Date(currentDate); expiryLimit.setDate(expiryLimit.getDate()+7);
  const [customers,projects,todayTasks,overdue,orders,receivables,quotes] = await Promise.all([
    supabase.from("customers").select("id",{count:"exact",head:true}).gte("created_at",`${month}-01`).is("deleted_at",null),
    supabase.from("opportunities").select("id",{count:"exact",head:true}).eq("status","已报价").is("deleted_at",null),
    supabase.from("tasks").select("id,title,due_at,priority,customers(company_name)").gte("due_at",`${today}T00:00:00`).lt("due_at",`${today}T23:59:59`).not("status","in",'(已完成,已取消)').limit(6),
    supabase.from("tasks").select("id,title,due_at,priority,customers(company_name)").lt("due_at",`${today}T00:00:00`).not("status","in",'(已完成,已取消)').limit(6),
    supabase.from("orders").select("sales_amount,sales_currency").gte("order_date",`${month}-01`).is("deleted_at",null),
    supabase.from("receivables").select("outstanding_amount").gt("outstanding_amount",0),
    supabase.from("supplier_quotations").select("id,quotation_number,valid_until,supplier_products(suppliers(company_name),products(product_name))").gte("valid_until",today).lte("valid_until",expiryLimit.toISOString().slice(0,10)).limit(5),
  ]);
  const orderTotal=(orders.data??[]).reduce((s,o)=>s+Number(o.sales_amount),0), outstanding=(receivables.data??[]).reduce((s,o)=>s+Number(o.outstanding_amount),0);
  const tasks=[...(overdue.data??[]),...(todayTasks.data??[])].slice(0,7);
  return <div className="space-y-8"><div><p className="text-[#b18436] text-sm tracking-wider">WELCOME BACK</p><h1 className="text-3xl font-semibold text-[#173b34] mt-1">Anne，今天也要认真跟进客户，努力成为小富婆。</h1><p className="text-neutral-500 mt-2">今天是 {new Intl.DateTimeFormat("zh-CN",{dateStyle:"full"}).format(new Date())}</p></div>
    <section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><StatCard label="今日待跟进" value={todayTasks.data?.length??0} hint="需要今天完成" tone="amber"/><StatCard label="已逾期任务" value={overdue.data?.length??0} hint="请优先处理" tone="red"/><StatCard label="本月新增客户" value={customers.count??0} hint="持续积累客户资产"/><StatCard label="已报价项目" value={projects.count??0} hint="等待客户回复" tone="amber"/><StatCard label="本月订单金额" value={money(orderTotal)} hint="人民币口径"/><StatCard label="当前待收款" value={money(outstanding)} hint="关注预计到账日" tone="amber"/><StatCard label="即将过期报价" value={quotes.data?.length??0} hint="未来 7 天" tone="red"/><StatCard label="本月净利润" value="—" hint="录入成本后自动计算"/></section>
    <section className="grid xl:grid-cols-2 gap-6"><div className="bg-white border border-[#e7dece] rounded-2xl"><div className="p-5 border-b flex justify-between"><h2 className="font-semibold text-[#173b34]">今日与逾期任务</h2><Link className="text-sm text-[#9a742d]" href="/tasks">查看全部 <ArrowRight className="inline" size={14}/></Link></div><div>{tasks.length?tasks.map((t)=><div key={t.id} className="p-4 border-b last:border-0 flex gap-3"><span className="mt-1">{new Date(t.due_at)<new Date()?<AlertTriangle size={17} className="text-red-500"/>:<CheckCircle2 size={17} className="text-amber-500"/>}</span><div><div className="font-medium">{t.title}</div><div className="text-xs text-neutral-500 mt-1">{shortDate(t.due_at)} · {t.priority}</div></div></div>):<div className="p-10 text-center text-neutral-400">今天没有待办，去开发新客户吧。</div>}</div></div>
      <div className="bg-white border border-[#e7dece] rounded-2xl"><div className="p-5 border-b"><h2 className="font-semibold text-[#173b34]">即将过期的供应商报价</h2></div><div>{quotes.data?.length?quotes.data.map((q)=><div key={q.id} className="p-4 border-b last:border-0 flex justify-between"><div><div className="font-medium">{q.quotation_number}</div><div className="text-xs text-neutral-500 mt-1">供应商报价需重新核实</div></div><span className="text-sm text-red-600">{shortDate(q.valid_until)} 到期</span></div>):<div className="p-10 text-center text-neutral-400">未来 7 天没有到期报价</div>}</div></div></section>
  </div>;
}

function LocalDashboard(){const customers=localRows("customers"),projects=localRows("opportunities"),tasks=localRows("tasks"),orders=localRows("orders"),now=new Date(),todayKey=shanghaiDateKey(now),active=(t:Record<string,unknown>)=>!["已完成","已取消"].includes(String(t.status));const today=tasks.filter(t=>String(t.due_at).slice(0,10)===todayKey&&active(t)),overdue=tasks.filter(t=>new Date(String(t.due_at))<now&&String(t.due_at).slice(0,10)!==todayKey&&active(t));const orderTotal=orders.reduce((s,o)=>s+Number(o.sales_amount),0),profit=orders.reduce((s,o)=>s+Number(o.net_profit_cny),0);return <div className="space-y-8"><div><p className="text-[#b18436] text-sm tracking-wider">LOCAL CRM · READY</p><h1 className="text-3xl font-semibold text-[#173b34] mt-1">Anne，今天也要认真跟进客户，努力成为小富婆。</h1><p className="text-neutral-500 mt-2">本地数据库已连接，所有数据保存在这台电脑。</p></div><section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><StatCard label="今日待跟进" value={today.length} hint="需要今天完成" tone="amber"/><StatCard label="已逾期任务" value={overdue.length} hint="请优先处理" tone="red"/><StatCard label="客户总数" value={customers.length} hint="本地客户资产"/><StatCard label="项目总数" value={projects.length} hint="持续推进"/><StatCard label="订单总金额" value={money(orderTotal)} hint="人民币口径"/><StatCard label="累计净利润" value={money(profit)} hint="自动计算"/><StatCard label="产品总数" value={localRows("products").length} hint="可搜索产品库"/><StatCard label="供应商总数" value={localRows("suppliers").length} hint="已录入供应商"/></section><section className="bg-white border border-[#e7dece] rounded-2xl"><div className="p-5 border-b flex justify-between"><h2 className="font-semibold text-[#173b34]">今日与逾期任务</h2><Link className="text-sm text-[#9a742d]" href="/tasks">查看全部 <ArrowRight className="inline" size={14}/></Link></div>{[...overdue,...today].slice(0,8).map(t=><div key={String(t.id)} className="p-4 border-b last:border-0 flex gap-3"><AlertTriangle size={17} className="text-red-500 mt-1"/><div><div className="font-medium">{String(t.title)}</div><div className="text-xs text-neutral-500 mt-1">{shortDate(String(t.due_at))} · {String(t.priority)}</div></div></div>)}</section></div>}
